---
# Final tasks after MISP is set up

- name: Allow apache to write to /var/www/MISP/app/tmp/logs
  command: chcon -R -t httpd_sys_rw_content_t /var/www/MISP/app/tmp/logs/

- name: "[Update php.ini] max_execution_time = 300"
  lineinfile:
    path: /etc/opt/rh/rh-php71/php.ini
    regexp: "^max_execution_time"
    line: "max_execution_time = 300"
    backrefs: yes

- name: "[Update php.ini] memory_limit = 512M"
  lineinfile:
    path: /etc/opt/rh/rh-php71/php.ini
    regexp: "^memory_limit"
    line: "memory_limit = 512M"
    backrefs: yes

- name: "[Update php.ini] upload_max_filesize = 50M"
  lineinfile:
    path: /etc/opt/rh/rh-php71/php.ini
    regexp: "^upload_max_filesize"
    line: "upload_max_filesize = 50M"
    backrefs: yes

- name: "[Update php.ini] post_max_size = 50M"
  lineinfile:
    path: /etc/opt/rh/rh-php71/php.ini
    regexp: "^post_max_size"
    line: "post_max_size = 50M"
    backrefs: yes

- name: Restart rh-php71 for settings to take effect
  systemd:
    name: rh-php71-php-fpm.service
    state: restarted

- name: Install pymisp and pydeep for Advanced Attachment Handler
  pip:
    name:
      - pymisp
      - git+https://github.com/kbandla/pydeep.git

- name: Install pymisp and maec in Python 3
  command: scl enable rh-python36 "pip3 install pymisp maec"
