---
# Setup tasks

- name: Enable the optional, extras and Software Collections (SCL) repos
  command:
  args:
    argv:
      - subscription-manager
      - repos 
      - --enable 
      - "{{ item }}"
  loop:
    - rhel-7-server-optional-rpms
    - rhel-7-server-extras-rpms
    - rhel-server-rhscl-7-rpms

- name: Install the deltarpm package to help reduce download size when installing updates
  yum:
    name: deltarpm
    state: latest

- name: Update the system
  yum:
    name: '*'
    state: latest

- name: Reboot the system
  reboot:

- name: Install the EPEL repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: latest
